### PR TITLE
add envoy gateway

### PR DESCRIPTION
**Pull request by arkodg**

### CODE REVIEW

**Comment by arkodg** [comment]
ptal @missBerg @phlax

**Review by nezdolik — APPROVED** [review]

**Review by phlax — APPROVED** [review]
lgtm, thanks @arkodg

**Comment by phlax** [comment]
hmm - actually the image is not showing in the preview https://deploy-preview-463--envoy-website.netlify.app/community

**Comment by phlax** [comment]
nm, thats a website bug

**Pull request merged**
