### PR TITLE
Adding Wise logo to Envoyproxy website

### PR DESCRIPTION
**Pull request by thejohnrichard**
We at Wise use envoy extensively and have contributed to the project in the past. 

Some public references:
- https://medium.com/wise-engineering/wise-tech-stack-2022-edition-a6ac089a382f
- https://youtu.be/4pfY0uFW7yk

### CODE REVIEW

**Comment by phlax** [comment]
could you fix DCO please @thejohnrichard

**Comment by thejohnrichard** [comment]
That does not seem quite right. I followed the instruction on the Details page for DCO though. Can you tell me how exactly I can fix the DCO @phlax ?

**Comment by phlax** [comment]
> In your local branch, run: git rebase HEAD~2 --signoff
> Force push your changes to overwrite the branch: git push --force-with-lease origin main

https://github.com/envoyproxy/envoy-website/pull/308/checks?check_run_id=13789941638

**Comment by thejohnrichard** [comment]
I tried that but it did not work. This did the trick though :)

`git reset --soft HEAD~2
git commit -am "Add wise logo to envoyproxy homepage" --signoff`

**Comment by thejohnrichard** [comment]
The color does not match though, I requested a new version from our design team.

**Comment by thejohnrichard** [comment]
@phlax. DCO is fixed and logo is now in the correct colors :)

**Pull request merged**
